name: Node CI

on: [push, pull_request]

jobs:
  old:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "ubuntu-16.04", "windows-latest", "windows-2016", "macOS-latest"]
    runs-on: ${{matrix.os}}
    steps:
    - run: |
        [ "$(ls -A $RUNNER_TOOL_CACHE)" ] && echo "Not Empty" || echo "Empty"
      shell: bash
