name: I was edited
on: [push, pull_request, pull_request_review]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: thboop/typescript-action@master
        with: 
          token: ${{github.token}}
          owner: thboop
          repo: test
